spring.application.name=nida-i

# Port du serveur web
server.port=8080

# Importe automatiquement le fichier local s'il est présent
# (ignoré silencieusement s'il n'existe pas, ex: en CI/CD)
spring.config.import=optional:file:local.properties

# Configuration de la base de données PostgreSQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Comportement de Hibernate
# 'update' met à jour le schéma sans détruire les données existantes
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect