name: CI Pipeline

# Déclenche le pipeline à chaque push sur une PR ou directement sur main
on:
  push:
    branches: [main]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Le serveur virtuel GitHub

    # On démarre une base de données éphémère pour que Spring Boot puisse charger son contexte
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: root
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    
    steps:
    # 1. On récupère le code source
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # 2. On installe Java 21 sur le serveur
    - name: Set up JDK 21
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven # Active le cache pour télécharger les dépendances plus vite aux prochains lancements

    # 3. On lance les tests Maven (avec les identifiants de la BDD éphémère injectés)
    - name: Build and Test
      env: 
        DB_URL: jdbc:postgresql://localhost:5432/test_db
        DB_USERNAME: postgres
        DB_PASSWORD: root
      run: mvn clean test -B

    # 4. On lance uniquement l'analyse SonarCloud AVEC le token
    - name: SonarCloud Scan
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -B

    # 5. Démarrage éphémère de l'API pour extraire la spécification OpenAPI
    - name: Extract OpenAPI JSON
      env: 
        DB_URL: jdbc:postgresql://localhost:5432/test_db
        DB_USERNAME: postgres
        DB_PASSWORD: root
      run: |
        mvn package -DskipTests -B
        java -jar target/*.jar &
        sleep 15
        curl -s http://localhost:8080/api-docs > openapi.json
        kill %1
      
    # 6. Génération du site statique Swagger UI
    - name: Generate Swagger UI
      uses: Legion2/swagger-ui-action@eff65dc3f193f0a749872be82f74baa35be0797d #v1
      with:
        output: swagger-ui
        spec-file: openapi.json
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    # 7. Déploiement sur GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 #v3
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        publish_dir: ./swagger-ui